{% set version = "0.2.2" %}

package:
  name: urbanaccess
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/urbanaccess/urbanaccess-{{ version }}.tar.gz
  sha256: a00ff67488eeec62d5c68bc07f1ee6cb62dc867ae0872241544dc2e924e28939

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - geopy >=1.11.0
    - matplotlib-base >=2.0
    - numpy >=1.11
    - osmnet >=0.1.4
    - pandana >=0.2.0
    - pandas >=0.17.0
    - python
    - pyyaml >=3.11
    - requests >=2.9.1
    - scikit-learn >=0.17.1
    - six >=1.11

test:
  imports:
    - urbanaccess
    - urbanaccess.gtfs
    - urbanaccess.osm

about:
  home: https://github.com/UDST/urbanaccess
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: License.txt
  summary: A tool for creating GTFS transit and OSM pedestrian networks for use in Pandana accessibility analyses

extra:
  recipe-maintainers:
    - ocefpaf
    - sablanchard
    - smmaurer
